default_language_version:
  python: python3

default_install_hook_types:
  - pre-commit
  - commit-msg
  - pre-push

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: commitizen-check
        name: commitizen check
        entry: uv run cz check --allow-abort --commit-msg-file
        language: system
        pass_filenames: true
        stages: [commit-msg]

      - id: ruff-check
        name: ruff check
        entry: uv run ruff check --fix --force-exclude
        language: system
        types_or: [python, pyi]

      - id: ruff-format
        name: ruff format
        entry: uv run ruff format --force-exclude
        language: system
        types_or: [python, pyi]

  - repo: https://github.com/facebook/pyrefly-pre-commit
    rev: 1.2.0.dev2  # Note: this is the version of the pre-commit hook, NOT the pyrefly version used for type checking
    hooks:
      - id: pyrefly-check
        name: Pyrefly (type checking)
        pass_filenames: false  # Recommended to do full repo checks. However, you can change this to `true` to only check changed files
        language: system  # Use system-installed pyrefly
